on:
  workflow_dispatch:

jobs:
  check-steps:
    name: test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@main

    - name: sh
      run: |
        mkdir test test2
        touch test/123 test/456 test2/abc test2/def
        touch aaa bbb
        mkdir test/test_ test/test_2
        touch test/test_2/111
        echo "RELEASE_TAG=test" >> $GITHUB_ENV
        echo "CDIR=$(pwd)" >> $GITHUB_ENV

        echo '=============================='
        env
        echo '=============================='
        echo '${{ toJSON(job) }}'
        echo '=============================='
        echo '${{ toJSON(runner) }}'
        echo '=============================='
        echo '${{ toJSON(github) }}'

    - name: test
      uses: ./
      with:
        gzip: false
        dir: true
        files: >
          test/*
          aaa
          test2/*
          ${{ env.CDIR }}/bbb
        allow_del: true
        allow_override: true

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
