name: TEST

on:
#  release:
#    types: [published]
#  push:
#    branches:
#    - master
#    paths:
#    - '.config'
#  schedule:
#    - cron: 0 23 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install jq

    - name: Touch something
      run: |
        mkdir some
        cd some
        touch some1 some2 some3

    - name: Upload to release for test
      uses: ./
      with:
        tag: test
        gzip: false
        files: >
          some/*
        allow_del: true
        allow_override: true

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 1
